### ISSUE TITLE
Does not work in incognito mode

### ISSUE THREAD

**Issue by johno1985** [benjaminoakes/TabCarousel#31] opened 2016-10-28 15:14 UTC
Hi, I am using Chromium Browser "Version 48.0.2564.82 Built on Ubuntu 15.04 running on Raspbian 8.0".

I can successfully cycle through the tabs however, when I switch on incognito mode, the tabs no longer switch.

Can you help?

**Comment by benjaminoakes** [comment] 2016-10-31 17:55
This is the first I've heard of an issue like this, but it's worth noting that you're running some out of date software.

* Ubuntu 15.04 has been unsupported since around the beginning of 2016
* Chromium 48 is 6 major releases behind the current release (I have Chrome 54 installed)

You should consider updating, as it may fix your issue.

When I tested the behavior you described on macOS 10.11.6 and Chrome 54.0.2840.71, it worked as expected.  Please make sure you have checked the "Allow in incognito" checkbox for TabCarousel under the "Extensions" settings.

**Comment by benjaminoakes** [comment] 2016-11-07 19:06
I am not able to reproduce this issue.  I'm closing it until there are reliable reproduction steps for the behavior described on an up-to-date version of Chrome/Chromium.

**Closed by benjaminoakes** 2016-11-07 19:06 UTC
